# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Slava Bezborodov
email: slava.bezborodoff@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My journey to exploring the world
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://slavabezborodov.com" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-163905546-1

donate_services:
  - yandex_money:
    type: yandex
    title: Yandex.Money
    description: Money from bank cards or from Yandex.Money Wallets including 0.5% commission
    config:
      wallet: 4100112640469842
      services:
        - amount: 100
          description: Cheap and simple
        - amount: 250
          description: Top up my phone balance
        - amount: 500
          description: One pizza for me
        - amount: 999
          description: Three nines
        - description: In fact, any donation makes me happier!
  - patreon:
    type: patreon
    title: Patreon
    description: >-
      I retain creative freedom while getting the salary I deserve,
      and you get to rest easy knowing that your money goes directly
      towards creating more of what you love

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- donate.md
- about.md

minima:
  social_links:
    # twitter: jekyllrb
    github: slava-bezborodoff
    # stackoverflow: "11111"
    # dribbble: jekyll
    facebook: slava.bezborodoff
    vk: slava.bezborodoff
    gmail: slava.bezborodoff@gmail.com
    # flickr: jekyll
    instagram: slava.bezborodoff
    linkedin: slava-bezborodoff
    # pinterest: jekyll
    telegram: slava_bezborodoff
    # microdotblog: jekyll
    # keybase: jekyll

    # mastodon:
    #  - username: jekyll
    #    instance: example.com
    #  - username: jekyll2
    #    instance: example.com

    # gitlab:
    #  - username: jekyll
    #    instance: example.com
    #  - username: jekyll2
    #    instance: example.com

    # youtube: jekyll
    youtube_channel: UCEmB1pIxkdIXeiu6ys9DJUw
    youtube_channel_name: Slava Bezborodov

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
